clear functions
test_IChi2

============================================
ICH12 AF3 TEST
============================================

Loading GAMEEMO dataset...

Building AF3 dataset...
This may take some time.

Starting IChi2...

Normalising features...
Calculating Chi-square ranking...

============================================
ICH12 ITERATIVE FEATURE SELECTION
============================================

  Features    Accuracy (%)            Loss
--------------------------------------------

Evaluating 100 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
       100           70.71          0.2929

Evaluating 200 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
       200           76.07          0.2393

Evaluating 300 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
       300           84.46          0.1554

Evaluating 400 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
       400           86.96          0.1304

Evaluating 500 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
       500           89.64          0.1036

Evaluating 600 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
       600           91.07          0.0893

Evaluating 700 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
       700           92.50          0.0750

Evaluating 800 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
       800           93.57          0.0643

Evaluating 900 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
       900           94.29          0.0571

Evaluating 1000 features...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
Training class 1 vs all...
Training class 2 vs all...
Training class 3 vs all...
Training class 4 vs all...
      1000           94.46          0.0554

============================================
ICH12 RESULT
============================================
Optimal feature count : 1000
Minimum loss         : 0.0554
Optimal accuracy     : 94.46 %

============================================
FINAL ICHI2 VALIDATION
============================================
Channel               : AF3
Instances             : 560
Original features     : 31744

Optimal feature count : 1000
Optimal accuracy      : 94.46 %
Minimum loss          : 0.0554

Dataset assembly time : 57.20 s
IChi2 processing time : 47.37 s

Optimal count range   : PASSED
Finite minimum loss   : PASSED

============================================
IChi2 TEST COMPLETED
============================================
